steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/build', '-f', 'gcb/Dockerfile', 'https://github.com/softappeal/yass.git' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', 'gcr.io/$PROJECT_ID/build', '/project/gcb/start.release.sh' ]
