# gcloud builds submit --config cloudbuild.release.yaml --substitutions=_CHECKOUT="dev.gcb",_PROJECT_VERSION="1.2.3" .
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/build', '-f', 'gcb/Dockerfile', 'https://github.com/softappeal/yass.git#${_CHECKOUT}' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '--env', 'PROJECT_VERSION=${_PROJECT_VERSION}', 'gcr.io/$PROJECT_ID/build', '/project/gcb/start.release.sh' ]
substitutions:
  _CHECKOUT:
  _PROJECT_VERSION:
